/**
 * Brief: STM32F746G-DISCOVERY
 **/

#include <stdint.h>

#include "utils/memory.h"
#include "board_heap_table.h"

#include "hal/hal_mcu.h"
#include "hal/hal_clock.h"
#include "hal/hal_gpio.h"
#include "hal/hal_dma.h"
#include "hal/hal_i2c.h"
#include "hal/hal_spi.h"
#include "hal/hal_emc.h"

#include "drivers/console/console_serial.h"
//#include "drivers/display/rk043fn48h.h"

/* -------------------------------------------------------------------- */
const HAL_ClkDesc_t g_pClkList[] = /* Overdrive ON */
{
    { 25000000,     (CLK_TYPE_OSC_EXT   | CLK_MAIN_OSC)  },
    { 216000000,    (CLK_TYPE_PLL0      | CLK_SRC_XTAL)  },
    { 216000000,    (CLK_TYPE_AHB       | CLK_SRC_PLL0)  },
    { 54000000,     (CLK_TYPE_APB1)                      },
    { 108000000,    (CLK_TYPE_APB2)                      },
    { 9600000,      (CLK_TYPE_LCDC)                      }, /* panel pixel clock */

    { 0, 0 } /* End of list */
};

/* -------------------------------------------------------------------- */
const HAL_GpioPin_t g_pPinList[] =
{
    /* Debug UART */
    GPIO_CONFIG(GPIOB, GPIO_BIT7, GPIO_AF7,         GPIO_IN_FLOAT),         // VCP_RX (USART1_RX)
    GPIO_CONFIG(GPIOA, GPIO_BIT9, GPIO_AF7,         GPIO_OUT_PUSH_PULL),    // VCP_TX (USART1_TX)

    /* MCO1/2 */
//  GPIO_CONFIG(GPIOA, GPIO_BIT8, GPIO_AF1,         GPIO_OUT_PUSH_PULL),    // MCO1
//  GPIO_CONFIG(GPIOC, GPIO_BIT9, GPIO_AF1,         GPIO_OUT_PUSH_PULL),    // MCO2

    /* */
    GPIO_CONFIG(GPIOD, GPIO_BIT10,  GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_D15
    GPIO_CONFIG(GPIOD, GPIO_BIT9,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_D14
    GPIO_CONFIG(GPIOD, GPIO_BIT8,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_D13
    GPIO_CONFIG(GPIOE, GPIO_BIT15,  GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_D12
    GPIO_CONFIG(GPIOE, GPIO_BIT14,  GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_D11
    GPIO_CONFIG(GPIOE, GPIO_BIT13,  GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_D10
    GPIO_CONFIG(GPIOE, GPIO_BIT12,  GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_D9
    GPIO_CONFIG(GPIOE, GPIO_BIT11,  GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_D8
    GPIO_CONFIG(GPIOE, GPIO_BIT10,  GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_D7
    GPIO_CONFIG(GPIOE, GPIO_BIT9,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_D6
    GPIO_CONFIG(GPIOE, GPIO_BIT8,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_D5
    GPIO_CONFIG(GPIOE, GPIO_BIT7,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_D4
    GPIO_CONFIG(GPIOD, GPIO_BIT1,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_D3
    GPIO_CONFIG(GPIOD, GPIO_BIT0,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_D2
    GPIO_CONFIG(GPIOD, GPIO_BIT15,  GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_D1
    GPIO_CONFIG(GPIOD, GPIO_BIT14,  GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_D0
    GPIO_CONFIG(GPIOG, GPIO_BIT1,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_A11
    GPIO_CONFIG(GPIOG, GPIO_BIT0,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_A10
    GPIO_CONFIG(GPIOF, GPIO_BIT15,  GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_A9
    GPIO_CONFIG(GPIOF, GPIO_BIT14,  GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_A8
    GPIO_CONFIG(GPIOF, GPIO_BIT13,  GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_A7
    GPIO_CONFIG(GPIOF, GPIO_BIT12,  GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_A6
    GPIO_CONFIG(GPIOF, GPIO_BIT5,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_A5
    GPIO_CONFIG(GPIOF, GPIO_BIT4,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_A4
    GPIO_CONFIG(GPIOF, GPIO_BIT3,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_A3
    GPIO_CONFIG(GPIOF, GPIO_BIT2,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_A2
    GPIO_CONFIG(GPIOF, GPIO_BIT1,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_A1
    GPIO_CONFIG(GPIOF, GPIO_BIT0,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_A0
    GPIO_CONFIG(GPIOG, GPIO_BIT5,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_BA1
    GPIO_CONFIG(GPIOG, GPIO_BIT4,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_BA0
    GPIO_CONFIG(GPIOH, GPIO_BIT5,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_SDNWE
    GPIO_CONFIG(GPIOG, GPIO_BIT15,  GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_SDNCAS
    GPIO_CONFIG(GPIOF, GPIO_BIT11,  GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_SDNRAS
    GPIO_CONFIG(GPIOH, GPIO_BIT3,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_SDNE0
    GPIO_CONFIG(GPIOC, GPIO_BIT3,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_SDCKE0
    GPIO_CONFIG(GPIOG, GPIO_BIT8,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_SDCLK
    GPIO_CONFIG(GPIOE, GPIO_BIT1,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_NBL1
    GPIO_CONFIG(GPIOE, GPIO_BIT0,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // FMC_NBL0

    /* External Camera connector */
    GPIO_CONFIG(GPIOH, GPIO_BIT9,   GPIO_AF13,      GPIO_IN_PULL_UP), // DCMI_D0
    GPIO_CONFIG(GPIOH, GPIO_BIT10,  GPIO_AF13,      GPIO_IN_PULL_UP), // DCMI_D1
    GPIO_CONFIG(GPIOH, GPIO_BIT11,  GPIO_AF13,      GPIO_IN_PULL_UP), // DCMI_D2
    GPIO_CONFIG(GPIOH, GPIO_BIT12,  GPIO_AF13,      GPIO_IN_PULL_UP), // DCMI_D3
    GPIO_CONFIG(GPIOH, GPIO_BIT14,  GPIO_AF13,      GPIO_IN_PULL_UP), // DCMI_D4
    GPIO_CONFIG(GPIOD, GPIO_BIT3,   GPIO_AF13,      GPIO_IN_PULL_UP), // DCMI_D5
    GPIO_CONFIG(GPIOE, GPIO_BIT5,   GPIO_AF13,      GPIO_IN_PULL_UP), // DCMI_D6
    GPIO_CONFIG(GPIOE, GPIO_BIT6,   GPIO_AF13,      GPIO_IN_PULL_UP), // DCMI_D7
    GPIO_CONFIG(GPIOA, GPIO_BIT6,   GPIO_AF13,      GPIO_IN_PULL_UP), // DCMI_PIXCK
    GPIO_CONFIG(GPIOA, GPIO_BIT4,   GPIO_AF13,      GPIO_IN_PULL_UP), // DCMI_HSYNC
    GPIO_CONFIG(GPIOG, GPIO_BIT9,   GPIO_AF13,      GPIO_IN_PULL_UP), // DCMI_VSYNC
    GPIO_CONFIG(GPIOH, GPIO_BIT13,  GPIO_AF_NONE,   GPIO_OUT_PUSH_PULL), // DCMI_PWR_EN

    /* LCD 4.3" with Capacitive Touch RK043FN48H-CT672B */
    GPIO_CONFIG(GPIOI, GPIO_BIT15,  GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_R0
    GPIO_CONFIG(GPIOJ, GPIO_BIT0,   GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_R1
    GPIO_CONFIG(GPIOJ, GPIO_BIT1,   GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_R2
    GPIO_CONFIG(GPIOJ, GPIO_BIT2,   GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_R3
    GPIO_CONFIG(GPIOJ, GPIO_BIT3,   GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_R4
    GPIO_CONFIG(GPIOJ, GPIO_BIT4,   GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_R5
    GPIO_CONFIG(GPIOJ, GPIO_BIT5,   GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_R6
    GPIO_CONFIG(GPIOJ, GPIO_BIT6,   GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_R7
    GPIO_CONFIG(GPIOJ, GPIO_BIT7,   GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_G0
    GPIO_CONFIG(GPIOJ, GPIO_BIT8,   GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_G1
    GPIO_CONFIG(GPIOJ, GPIO_BIT9,   GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_G2
    GPIO_CONFIG(GPIOJ, GPIO_BIT10,  GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_G3
    GPIO_CONFIG(GPIOJ, GPIO_BIT11,  GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_G4
    GPIO_CONFIG(GPIOK, GPIO_BIT0,   GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_G5
    GPIO_CONFIG(GPIOK, GPIO_BIT1,   GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_G6
    GPIO_CONFIG(GPIOK, GPIO_BIT2,   GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_G7
    GPIO_CONFIG(GPIOE, GPIO_BIT4,   GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_B0
    GPIO_CONFIG(GPIOJ, GPIO_BIT13,  GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_B1
    GPIO_CONFIG(GPIOJ, GPIO_BIT14,  GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_B2
    GPIO_CONFIG(GPIOJ, GPIO_BIT15,  GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_B3
    GPIO_CONFIG(GPIOG, GPIO_BIT12,  GPIO_AF9,       GPIO_OUT_PUSH_PULL), // LCD_B4
    GPIO_CONFIG(GPIOK, GPIO_BIT4,   GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_B5
    GPIO_CONFIG(GPIOK, GPIO_BIT5,   GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_B6
    GPIO_CONFIG(GPIOK, GPIO_BIT6,   GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_B7
    GPIO_CONFIG(GPIOI, GPIO_BIT14,  GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_CLK
    GPIO_CONFIG(GPIOI, GPIO_BIT10,  GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_HSYNC
    GPIO_CONFIG(GPIOI, GPIO_BIT9,   GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_VSYNC
    GPIO_CONFIG(GPIOK, GPIO_BIT7,   GPIO_AF14,      GPIO_OUT_PUSH_PULL), // LCD_DE

    GPIO_CONFIG(GPIOI, GPIO_BIT12,  GPIO_AF_NONE,   GPIO_OUT_PUSH_PULL), // LCD_DISP
    GPIO_CONFIG(GPIOK, GPIO_BIT3,   GPIO_AF_NONE,   GPIO_OUT_PUSH_PULL), // LCD_BL_CTRL
    GPIO_CONFIG(GPIOI, GPIO_BIT13,  GPIO_AF_NONE,   GPIO_IN_PULL_UP), // LCD_INT - From touch panel

    /* Shared I2C3: LCD Touch + Audio Codec */
    GPIO_CONFIG(GPIOH, GPIO_BIT7,   GPIO_AF4,       GPIO_OUT_OPEN_DRAIN), // LCD_SCL, AUDIO_SCL
    GPIO_CONFIG(GPIOH, GPIO_BIT8,   GPIO_AF4,       GPIO_OUT_OPEN_DRAIN), // LCD_SDA, AUDIO_SDA

    /* Shared I2C1: Camera + ExtI2C + Arduino UNO */
    GPIO_CONFIG(GPIOB, GPIO_BIT9,   GPIO_AF4,      GPIO_OUT_OPEN_DRAIN), // DCMI_SDA, EXT_SDA, ARD_D14
    GPIO_CONFIG(GPIOB, GPIO_BIT8,   GPIO_AF4,      GPIO_OUT_OPEN_DRAIN), // DCMI_SCL, EXT_SCL, ARD_D15

    /* LAN8742A-CZ-TR */
    GPIO_CONFIG(GPIOG, GPIO_BIT11,  GPIO_AF11,      GPIO_OUT_PUSH_PULL),    // RMII_TX_EN
    GPIO_CONFIG(GPIOG, GPIO_BIT13,  GPIO_AF11,      GPIO_OUT_PUSH_PULL),    // RMII_TXD0
    GPIO_CONFIG(GPIOG, GPIO_BIT14,  GPIO_AF11,      GPIO_OUT_PUSH_PULL),    // RMII_TXD1
    GPIO_CONFIG(GPIOC, GPIO_BIT4,   GPIO_AF11,      GPIO_IN_FLOAT),         // RMII_RXD0
    GPIO_CONFIG(GPIOC, GPIO_BIT5,   GPIO_AF11,      GPIO_IN_FLOAT),         // RMII_RXD1
    GPIO_CONFIG(GPIOG, GPIO_BIT2,   GPIO_AF_NONE,   GPIO_IN_PULL_UP),       // RMII_RXER
    GPIO_CONFIG(GPIOA, GPIO_BIT7,   GPIO_AF11,      GPIO_IN_PULL_UP),       // RMII_CRS_DV
    GPIO_CONFIG(GPIOC, GPIO_BIT1,   GPIO_AF11,      GPIO_OUT_PUSH_PULL),    // RMII_MDC
    GPIO_CONFIG(GPIOA, GPIO_BIT2,   GPIO_AF11,      GPIO_OUT_PUSH_PULL),    // RMII_MDIO
    GPIO_CONFIG(GPIOA, GPIO_BIT1,   GPIO_AF11,      GPIO_IN_PULL_UP),       // RMII_REF_CLK

    /*  USB OTG HS PHY with Micro A-B connector */
// OTG_HS_OverCurrent
// ULPI_NXT
// ULPI_DIR
// ULPI_STP
// ULPI_CK
// ULPI_D7
// ULPI_D6
// ULPI_D5
// ULPI_D4
// ULPI_D3
// ULPI_D2
// ULPI_D1
// ULPI_D0

    /* USB OTG FS with Micro A-B connector */
// OTG_FS_PowerSwitchOn
// OTG_FS_OverCurrent
// OTG_FS_VBUS
// OTG_FS_N
// OTG_FS_P
// OTG_FS_ID

    /* Quad SPI Flash Memory N25Q128A13EF840E */
    GPIO_CONFIG(GPIOB, GPIO_BIT6,   GPIO_AF10,      GPIO_OUT_PUSH_PULL), // QSPI_NCS (QUADSPI_BK1_NCS)
    GPIO_CONFIG(GPIOB, GPIO_BIT2,   GPIO_AF9,      GPIO_OUT_PUSH_PULL), // QSPI_CLK
    GPIO_CONFIG(GPIOD, GPIO_BIT11,  GPIO_AF9,      GPIO_IN_PULL_UP), // QSPI_D0 (QUADSPI_BK1_IO0)
    GPIO_CONFIG(GPIOD, GPIO_BIT12,  GPIO_AF9,      GPIO_IN_PULL_UP), // QSPI_D1
    GPIO_CONFIG(GPIOE, GPIO_BIT2,   GPIO_AF9,      GPIO_IN_PULL_UP), // QSPI_D2 (QUADSPI_BK1_IO2)
    GPIO_CONFIG(GPIOD, GPIO_BIT13,  GPIO_AF9,      GPIO_IN_PULL_UP), // QSPI_D3

    /* Audio Codec WOLFSON WM8994ECS/R */
    GPIO_CONFIG(GPIOI, GPIO_BIT4,   GPIO_AF10,      GPIO_OUT_PUSH_PULL), // SAI2_MCLKA
    GPIO_CONFIG(GPIOI, GPIO_BIT5,   GPIO_AF10,      GPIO_OUT_PUSH_PULL), // SAI2_SCKA
    GPIO_CONFIG(GPIOI, GPIO_BIT6,   GPIO_AF10,      GPIO_OUT_PUSH_PULL), // SAI2_SDA
    GPIO_CONFIG(GPIOI, GPIO_BIT7,   GPIO_AF10,      GPIO_IN_PULL_UP), // SAI2_FSA
    GPIO_CONFIG(GPIOG, GPIO_BIT10,  GPIO_AF10,      GPIO_IN_PULL_UP), // SAI2_SDB
    GPIO_CONFIG(GPIOD, GPIO_BIT6,   GPIO_AF_NONE,   GPIO_IN_PULL_UP), // Audio_INT
    GPIO_CONFIG(GPIOD, GPIO_BIT7,   GPIO_AF8,       GPIO_IN_PULL_UP), // SPDIF_RX0

    /* MICRO-SD */
    GPIO_CONFIG(GPIOC, GPIO_BIT8,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // uSD_D0
    GPIO_CONFIG(GPIOC, GPIO_BIT9,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // uSD_D1
    GPIO_CONFIG(GPIOC, GPIO_BIT10,  GPIO_AF12,      GPIO_OUT_PUSH_PULL), // uSD_D2
    GPIO_CONFIG(GPIOC, GPIO_BIT11,  GPIO_AF12,      GPIO_OUT_PUSH_PULL), // uSD_D3
    GPIO_CONFIG(GPIOC, GPIO_BIT12,  GPIO_AF12,      GPIO_OUT_PUSH_PULL), // uSD_CLK
    GPIO_CONFIG(GPIOD, GPIO_BIT2,   GPIO_AF12,      GPIO_OUT_PUSH_PULL), // uSD_CMD
    GPIO_CONFIG(GPIOC, GPIO_BIT13,  GPIO_AF_NONE,   GPIO_IN_PULL_UP), // uSD_Detect

    /* EXT/RF E2P Connector */
    GPIO_CONFIG(GPIOG, GPIO_BIT3,   GPIO_AF_NONE,   GPIO_OUT_PUSH_PULL), // EXT_RST

    /* USER & WAKE-UP Button */
    GPIO_CONFIG(GPIOI, GPIO_BIT11,  GPIO_AF_NONE,   GPIO_IN_PULL_UP), // B_USER

    /* Arduino UNO connector */
    //GPIO_CONFIG(GPIOA, GPIO_BIT0, GPIO_AF_NONE, GPIO_IN_FLOAT), // ARD_A0
// ARD_A1
// ARD_A2
// ARD_A3
// ARD_A4
// ARD_A5
    GPIO_CONFIG(GPIOI, GPIO_BIT1,   GPIO_AF_NONE, GPIO_OUT_PUSH_PULL),  // ARD_D13 - LD1
// ARD_D12
// ARD_D11
// ARD_D10
// ARD_D9
// ARD_D8
// ARD_D7
// ARD_D6
// ARD_D5
// ARD_D4
// ARD_D3
// ARD_D2
// ARD_D1
// ARD_D0

    /* End of list */
    GPIO_CONFIG(NULL, 0, 0, 0)
};

/* -------------------------------------------------------------------- */
/* MT48LC4M32B2B5-6A */
const HAL_EMC_SDRAM_Config_t g_pMT48LC4M32B2B5 =
{
    .nCS        = 0, /* FMC_SDNE0 */
    .nIntBanks  = 4,
    .nColBits   = 8,
    .nRowBits   = 12,
    .nDataBits  = 16,
    .nRows      = 4096,

    /* Timings */
    .tCK        = 6,
    .tRefresh   = 64000000, /*64ms*/
    .tRP        = 2,
    .tRC        = 6,
    .tRCD       = 2,
    .tWR        = 2,
    .tXSR       = 6,
    .tMRD       = 2,
    .tRAS       = 4,
    .tCASd      = 3,
};

const HAL_EmcMem_t g_EMC_MemList[] =
{
    {EMC_MEM_SDRAM, 0xC0000000, 0x00800000, &g_pMT48LC4M32B2B5},
    /* End of list */
    {0, 0, 0, NULL}
};

/* ------------------------------------------------------------------ */
const HAL_DMA_Map_t g_pDMA_MapTable[] =
{
    /* End of list */
    DMA_MAP(NULL, NULL, NULL, 0, 0)
};

/* -------------------------------------------------------------------- */
const DRV_SerialConsoleDesc_t g_pSerialConsole =
{
    .pPort = USART1,
    .nBaudrate = 115200
};


/* -------------------------------------------------------------------- */
#if 0
const RK043FN48H_Desc_t g_pRK043FN48H =
{
    .EnablePin = { GPIOI, GPIO_BIT12 },
    .BacklightPin = { GPIOK, GPIO_BIT3 },
    .Orientation = e_DISP_CW_0,
    .Fmt = e_DISP_CF_RGB_565
};
#endif

